version: "3.8"
services:
  nginx:
    restart: always
    image: nginx:1-alpine
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
